In [1]:
import pandas as pd

In [3]:
single_tumor_cases = pd.read_json("data/single_tumor_cases.json")
single_tumor_cases

              0
0    case_00000
1    case_00003
2    case_00004
3    case_00005
4    case_00007
..          ...
322  case_00581
323  case_00582
324  case_00583
325  case_00585
326  case_00588

[327 rows x 1 columns]

In [13]:
annotation = pd.read_csv("data/kits23 JSON table - JSON.csv")
annotation.columns
annotation = annotation[['case_id', 'position of tumor', 'Invasion of the renal sinus', 'radius']]

# Drop rows where ANY of the specified columns have a NaN value
annotation = annotation.dropna(subset=['position of tumor', 'Invasion of the renal sinus'])

# Optional: Reset the index if you want the numbers on the left to be sequential again
annotation = annotation.reset_index(drop=True)

annotation

        case_id position of tumor Invasion of the renal sinus  radius
0    case_00000        Peripheral                 Noninvasive     0.0
1    case_00003        Peripheral                 Noninvasive     1.0
2    case_00004        Peripheral                 Noninvasive     1.0
3    case_00005             Hilar               Semi-invasive     2.0
4    case_00007        Peripheral                 Noninvasive     1.0
..          ...               ...                         ...     ...
187  case_00501        Peripheral                 Noninvasive     NaN
188  case_00518           Central                    Invasive     NaN
189  case_00525        Peripheral                 Noninvasive     NaN
190  case_00528        Peripheral                 Noninvasive     NaN
191  case_00533           Central                    Invasive     NaN

[192 rows x 4 columns]